---
- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Update the system
  ansible.builtin.apt:
    update_cache: true

- name: Restart SystemD
  ansible.builtin.systemd:
    daemon_reload: true


- name: Restart SonarQube
  ansible.builtin.systemd:
    name: sonar
    state: restarted


