apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve
  labels:
    app: ivolve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ivolve
  template:
    metadata:
      labels:
        app: ivolve
    spec:
      containers:
      - name: ivolve
<<<<<<< Updated upstream
        image: gohary101/ivolve-app:38
=======
        image: gohary101/ivolve-app:38
>>>>>>> Stashed changes
        ports:
        - containerPort: 8081
