plugin: aws_ec2
regions:
  - us-east-1        # Replace with your AWS region
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag    
hostnames:
  - ip-address # Use the public IP address as the hostname
  - tags